name: Build ThunderNanoServices on Linux

on:
  push:
    # branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Thunder:
    uses: VeithMetro/Thunder/.github/workflows/Linux build template.yml@development/actions

  ThunderInterfaces:
    needs: Thunder
    uses: rdkcentral/ThunderInterfaces/.github/workflows/Build ThunderInterfaces on Linux.yml@master

  ThunderNanoServices:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderNanoServices/.github/workflows/Linux build template.yml@development/actions
